AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  NewCops: enable
  SuggestExtensions: False

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/LineLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: False

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


Metrics/AbcSize:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Enabled: False

Metrics/MethodLength:
  Enabled: False


Naming/FileName:
  Exclude:
    - lib/mnemosyne-ruby.rb


# Single attr_reader statements allow easy documentation of attributes.
Style/AccessorGrouping:
  Enabled: False

Style/Documentation:
  Enabled: False

Style/HashEachMethods:
  Enabled: False

Style/HashTransformKeys:
  Enabled: False

Style/HashTransformValues:
  Enabled: False

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/Semicolon:
  Exclude:
    - '**/*_spec.rb'

Style/RescueModifier:
  Exclude:
    - '**/*_spec.rb'
