name: Lint
on:
  - pull_request
  - push

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_WITHOUT: development,test
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop --parallel --color
